
format = """\
[](bg:directory_bg)\
$directory\
[](fg:directory_bg bg:git_bg)\
$git_branch\
$git_state\
$git_status\
[](fg:git_bg)\
$fill\
$nodejs\
$cmd_duration $jobs\
$line_break
$character\
"""

palette = 'dein'

[palettes.dein]
directory_bg = '#006891'
directory_fg = '#dbdfe5'
directory_read_only = '#6ba1f2'
git_bg = '#242d3c'
git_fg = '#6ba1f2'
git_icon = '#dbdfe5'
git_fg_added = 'green'
git_fg_deleted = 'red'
node_bg = '#689d6a'
node_fg = '#0e0e0e'
node_icon = '#dbdfe5'
duration_bg = '#d79920'
duration_fg = '#dbdfe5'
jobs_bg = '#d65c0e'
jobs_fg = '#dbdfe5'

[directory]
format = '[$read_only]($read_only_style)[ $path]($style)'
read_only = " "
read_only_style = "bg:directory_bg fg:directory_read_only"
style = "bg:directory_bg fg:directory_fg"
truncation_length = 3
truncation_symbol = '…/'
fish_style_pwd_dir_length = 2
truncate_to_repo = true

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ''
'Music' = ''
'Pictures' = ''
"Developer" = '󱌢'

[git_branch]
symbol = "  "
format = "[$symbol](bg:git_bg fg:git_icon)[$branch ]($style)"
style = "bg:git_bg fg:git_fg"

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "bg:git_bg fg:git_icon"
conflicted = "󰢪 "
untracked = "󰘓 "
stashed = "󰪶 "
modified = " "
staged = " "
deleted = "󰮘 "
renamed = "󱇧 "

[git_state]
format = '\([$state($progress_current/$progress_total) ]($style)\)'
style = "bg:git_bg fg:git_fg"

[fill]
symbol = " "

[nodejs]
format = "[](node_bg)[$symbol](bg:node_bg fg:node_icon)[($version )]($style)"
style = "bg:node_bg fg:node_fg"

[cmd_duration]
format = "[ $duration ]($style)"
style = "bg:duration_bg fg:duration_fg"

[jobs]
symbol = ""
style = "bg:jobs_bg fg:jobs_fg"
number_threshold = 1
format = "[ $symbol ]($style)"

[line_break]
disabled = true

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](purple)"
